### ISSUE TITLE
EPIC_Components: Leg Y-up  world flip issue

### ISSUE THREAD

**Issue by miquelcampos** [mgear-dev/mgear#10]
Reported on  the forum http://forum.mgear-framework.com/t/question-about-epic-guides/2151/7

**Comment by JaschaW** [comment]
@miquelcampos do you know if this is a component or solver bug?

**Comment by miquelcampos** [comment]
@JaschaW is a component bug.

**Comment by JaschaW** [comment]
@miquelcampos Thanks! Looking at the rig build, the "leg_L0_tws0_loc" the scale attributes are set to 0, 1, 1. Setting all back to 1, removes that popping.

**Comment by miquelcampos** [comment]
@JaschaW yes, but I want to keep the tangent to the minimum, to reduce the translation in another axis different to X.

**Comment by JaschaW** [comment]
@miquelcampos I think I might not fully understand the underlying logic. Would like to maybe chat about this in detail and come up with a better understanding and a possible solution?
