### ISSUE TITLE
Shifter Game Tools: FBX exporter

### ISSUE THREAD

**Issue by miquelcampos** [mgear-dev/mgear#117]
- [x] old game tools in a tab named "disconnect"
- [ ] New main tab FBX export

Root motion options
~~- [ ] Space recorder options to edit root motion joint~~

FBX export options:

- [x] remove namespaces in FBX (using FBX SDK)
- [x] update hierarchy in FBX (using FBX SDK)
- [x] Export animation clips
- [x] Selection of up Axis Y or Z
- [ ] ~~Configuration script path for more options configuration~~
- [x] export/import tool options and clips configuration
- [x] Skeletal Mesh partition for Modular characters

Feature requests

The ability to set the animation layers we want on export. For example, if I make a run cycle and then make left and right variations on different layers, then export 3 different clips in one click, each one with its own unique animation layers active

~~Different tabs for different characters’ export settings (or a dropdown, but I personally prefer tabs)~~  We can achieve tabs by opening different instances and docking it

Quality of life requests

A) quickly check/uncheck all the anim clips to be exported (this is useful for doing things like directional aim poses where we often have to export a lot of assets at once)
B) Set the playback range to the time range that's in the exported clip
  - the option to also set the export range to the playback range would be welcome\
  

-  would it be possible to have an option that sets the export path to the current Maya file, and the name of the FBX as the name of the Maya file?
Yes, Also we can use tokens like {scene_name} or {scene_path}

SkeletalMesh partitions MEMO to research:

- [ ] FBX skinning mapping is by index? (check if this is true)
- [ ] If it is true, maybe cleaning joint hierarch will break index order?
- [ ] deleting not needed joint should be optional?

**Comment by miquelcampos** [comment]
WIP UI:
![image](https://user-images.githubusercontent.com/1050212/215931386-b13711d1-b600-4622-b6b6-7c86f9d50c60.png)

**Comment by miquelcampos** [comment]
![image](https://user-images.githubusercontent.com/1050212/220528046-bab4598d-bd9b-42d8-9295-306dab51c418.png)

**Comment by tpoveda** [comment]
![image](https://user-images.githubusercontent.com/6875035/222338375-1c4a8260-db4a-4a1a-9bd5-0539f53741d3.png)

**Comment by tpoveda** [comment]
Improvements after FBX Exporter review meeting:

- [x] Top list should keep its size when UI is expanded. Partitions list is the one that should be updated.
- [x] Allow the selection of multiple partitions.
- [x] Implement drag&drop partitions functionailty (left click: move partitions ; right click: duplicate partitions).
- [x] Store UI state when FBX Exporter tool is closed.
- [x] Load UI state when FBX Exporter tool is closed.
- [x] Remove full FBX when partitions are used.
- [x] Remove grab functionality from empty partitions.
- [x] Fix skeletal mesh exports.
- [x] Add support for animation layers.
- [x]  List of available Unrelal Skeletons should be available within UI.
- [ ] Master partition should be renamable and its data should be stored within scene.
- [ ] Make sure all export process can be scripted.
- [x] Implement FBX Exporter prestes loading/saving functionality.
- [ ] ~~Master partition should contain the full skeleton and if no geometry is available an empty triangle should be created and skinned to the root joint.~~

**Comment by SimonBenAnderson** [comment]
- Do we want `base animation` Layer, from Maya animation layer UI?

- [x] Update the Export > Animation > Drop down menu, with all the latest animation layers in Maya. Currently does not refresh.
- [ ] ~~Looks like each `Animation Clip` is a unique instance of the object. This should be made into a datamodel structure, where the data is stored outside of each instance, allowing for easier updating of UI elements. [Investigate further]~~ For turn around time, this is not needed, and has no impact.

**Comment by SimonBenAnderson** [comment]
- Custom DropDown created, that refreshes on popup. https://github.com/mgear-dev/mgear4/commit/4a1ff7b9ca4f5d91a05a365cf45562727378c4a1
- Timeline resizes matches playback area.

**Comment by SimonBenAnderson** [comment]
Sub task: 
Serialising Partitions #315 
Unreal Import with Skeleton #309
