### ISSUE TITLE
EPIC_leg_01 flips in some situation

### ISSUE THREAD

**Issue by dustinhu93** [mgear-dev/mgear#14]
As described in the title.
Happens especially when rotating the whole character in world space.
I did a test using the MetaHuman template and it occurred as well.
<img width= "75%" src = "https://user-images.githubusercontent.com/3250174/121030617-9ae37180-c7e4-11eb-8c09-cff066f2ef62.gif"/>
https://github.com/mgear-dev/shifter_epic_components/blob/23743e15e3feb5fad435da950de4c1a2758db881/scripts/mgear/shifter_epic_components/EPIC_leg_01/__init__.py#L656-L657
These lines seem to be the cause of the problem
But turns out those changes are made to address another issue from [here](http://forum.mgear-framework.com/t/epic-spine-module-and-the-epic-arm-module-joint-orient-issues/2077)

@miquelcampos maybe take a look when you have time ;)

**Comment by dustinhu93** [comment]
@miquelcampos great!
So should I close this one ? or leave it as a reminder?

**Comment by miquelcampos** [comment]
@dustinhu93 Please don't delete it :)
