### ISSUE TITLE
ueGear Plugin Setup

### ISSUE THREAD

**Issue by tpoveda** [mgear-dev/mgear#146]
Investigate how to create an Unreal Plugin that we can be used to deploy ueGear Plugin through Unreal Marketplace.

- [x] Create ueGear plugin using Unreal Plugin Editor.
- [x] Create init_unreal.py to bootstrap ueGear plugin in the Python side.
- [x] Investigate how to streamline the setup of the ueGear plugin in the Python side (automatize the addition of ueGear Python code to Unreal Startup Path settings for example).
- [x] Investigate how to package ueGear plugin.
- [x] Streamline the packaging process for different Unreal Engine versions.
- [ ] Create ueGear Unreal Marketplace Account @miquelcampos .
- [ ] Create ueGear Plugin Product Page (this is needed to generate a MarketplaceURL)

**Comment by SimonBenAnderson** [comment]
The .bat build for windows, now builds with 5.4 and 5.5
