### ISSUE TITLE
ueGear Bridge (Maya <==> Unreal)

### ISSUE THREAD

**Issue by tpoveda** [mgear-dev/mgear#147]
- [x] Enable Remote Remote Control Plugin API and add it as plugin dependency.
- [x] Send transform information from Maya to Unreal.
- [x] Send transform information from Unreal to Maya.
- [x] Send camera data from Maya to Unreal (position and maybe camera settings?)
- [x] Send camera data from Unreal to Maya.
- [x] Send geometry data from Maya to Unreal (export geo as FBX temp file and import it into Unreal automatically).
- [x] Send geometry data from Unreal to Maya.
- [ ] ~~Send material data from Maya to Unreal.~~
- [ ] ~~Send material data from Unreal to Maya.~~
- [ ] ~~Send texture data from Maya to Unreal.~~
- [ ] ~~Send texture data from Unreal to Maya.~~

**Comment by miquelcampos** [comment]
![image](https://user-images.githubusercontent.com/1050212/211755561-481f73d1-9e04-405f-a62d-6d54241035e6.png)

**Comment by tpoveda** [comment]
# Export Camera from Unreal Sequencer into FBX

The objective is simple, being able to export an Unreal Camera into an FBX, so we can import it again into other DCCs such us Maya.

---

This can be done manually by opening a Level Sequence into the Sequencer and then going into Actions -> Export...

![](https://i.imgur.com/4WajUjC.png)

This operation will export a FBX file that can be imported into Maya and will keep the animations in both the transform and the specific animated camera properties (such as the focal lenght).

---

## Exporting Sequence Cameras using Python API

API Documentation: https://docs.unrealengine.com/5.1/en-US/PythonAPI/class/SequencerTools.html

Unreal Python API exposes a function called `unreal.SequencerTools.export_level_sequence_fbx` that allows to export specific sequence binding and tracks into an FBX file. 

In the Unreal Engine Python API examples located here: `C:\Program Files\Epic Games\UE_5.1\Engine\Plugins\MovieScene\SequencerScripting\Content\Python` there are some examples about how to use Sequencer Python API within `sequencer_fbx_examples.py` file.

Within Unreal, you can execute the following code to export a Sequence into a FBX file:
```
import sequencer_fbx_examples
sequencer_fbx_examples.export_fbx("/Game/Assets/Levels/Showcase","/Game/Assets/Cinematics/shot0010_001", "/Game/Assets/Cinematics/SequenceMaster", "E:\\uegear\\FBX_Test.fbx")
```

In this example, the shot has a camera binding with some tracks for the camera:
![](https://i.imgur.com/yrnOjkk.png)


If you try to import the generated FBX into Maya you will notice that the generated FBX contains a transform one for each one of the animated tracks. This information is not useful.

![](https://i.imgur.com/45ZWkL5.png)

---

## Exporting Sequence Cameras using C++

All the functionality used to export Cameras using the Sequencer UI (throug the Actions -> Export... option) can be found in the following file: `C:\Program Files\Epic Games\UE_5.1\Engine\Source\Editor\Sequencer\Private\Sequencer.cpp`

More specifically in the function called `ExportFBX`. 

We tried to implement it in the following way:
 - Try to replicate the functionality implemented in that function and integrate within the ueGear C++ plugin. The problem is that we found a lot of dependencies with the Sequencer itself, so moving that functionality out of the Sequencer and implement it within the plugin was not straightfoward at all.

## Conclusion

For now, I would wait until Epic Games exposes this functionality into the Unreal Python API. Meanwhile, as a temporal workaround, I would include an option into Maya ueGear that can automatically import an FBX camera previsouly exported by the user manually.

**Comment by SimonBenAnderson** [comment]
**Note:**
### Camera Data in Unreal can be transient. 
In other words a Camera in an Unreal Level (Scene) does not always exist in the Level.  This is due to Unreal allowing Cameras to be virtual, generating them on the fly as you play a Sequence. 
  - If the Sequencer is closed No camera exists in the level. 
  - if the Sequencer is open and the current frame is over an empty clip or a clip that has no camera assigned. No Camera exists.

This will need to be taken into account for a full featured Camera Sync.

**Comment by SimonBenAnderson** [comment]
From working with Sequencer before, I think that this data is available, but it gets nested quite heavily into the clip information.

You can access the Current Level Sequence by
```Python
unreal.LevelSequenceEditorBlueprintLibrary
```
From there you have to handle each clip and the timeline. This is where is can get a bit complicated with juggling clip data.

**Comment by SimonBenAnderson** [comment]
Did some testing regarding the FBX export. 
- If you export the **CameraActor** (Object in Level) then the data in Maya gets imported correctly.
- If you export **CameraComponent** (Class's Subclass) then the data in Maya is a bunch of groups as you have exported meta-data about the object and not the object itself.

**Note:** As the exported data is only the camera data, Maya does not know the star and end frame of the LevelSequence shot. This data would need to be exported as some sort of accompanying `xml` or `json`.

**Comment by SimonBenAnderson** [comment]
There are also 3 types of possible Camera Tracks
1. SubSequence
2. Level Sequence Instance
3. Level Actor

Example image below, showing of animated Camera data in the level sequence.
![Screenshot 2023-09-08 at 1 57 05 PM](https://github.com/mgear-dev/mgear4/assets/1195751/ccbd37ea-d435-441c-8304-68cb6425d802)

We will need to capture every camera and check which correlates to the imported/Exported Maya Camera, so we can update it correctly.

**Comment by SimonBenAnderson** [comment]
Using `Unreal 5.2`, `Maya 2024` and `FBX 2020` 
The following is a manual export of Asset and Camera, with animated transform and focal length.

- Asset was selected from Level viewport and exported using `File > Export Selected`
- Camera was selected from Sequencer, CameraActor track, `Right Click Menu > Export`

Both seem to be matching:
![Screenshot 2023-09-08 at 2 11 35 PM](https://github.com/mgear-dev/mgear4/assets/1195751/07604df0-192e-41fb-8bdc-65ae61c4f5ea)
left: Maya Viewport       right: Unreal Viewport

**Comment by SimonBenAnderson** [comment]
If you try and export a `Instance Camera` from the `Sequencer`, and the timeline is not on or over a section of the Spawnable Camera Clip, in other words, no Camera has been spawned in the Level. Then exporting the camera will result in a `Component Like` export. where the imported FBX file in maya will generate multiple groups instead of a camera.

- Frames will not be exported for a Camera in Sequencer if the frames are outside of the `Active Range` _(Green and Red Lines)_

**Comment by SimonBenAnderson** [comment]
This looks to be completed by the following PRs
mGear: https://github.com/mgear-dev/mgear4/pull/281
ueGear: https://github.com/mgear-dev/ueGear/pull/5
