### ISSUE TITLE
RBF Manager: import errors when 'drivenControlName' is null

### ISSUE THREAD

**Issue by dmunix** [mgear-dev/mgear#149]
There seem to be an issue that stops the import of rbf files if the driven node is not a transform node. 
This was introduced with this [rigbits commit](https://github.com/mgear-dev/rigbits/commit/8870346c6109daae7ed155b80975fd1cf2c41790) ( which is now on mgear4 as well ) which checks if the node that was connected to the "scale" attribute to the RBF exists in scene.

This scale attribute is automatically connected to a new "RBF Multiplier" attribute created by the RBF Manager during the setup of new driven node and stored by the metadata under the "drivenControlName" key. The problem is that unless the driven node is a transform ending in "_driven", the metadata related to it during the export of a rbf setup is set to "null", resulting in the cmds.objExists to error.

**Comment by miquelcampos** [comment]
Thanks for the feedback @dmunix  I have added the bug ticket to the current WIP project

**Comment by miquelcampos** [comment]
fixed in #150
