### ISSUE TITLE
drag_n_drop_install script bug

### ISSUE THREAD

**Issue by ypypjay** [mgear-dev/mgear#154]
In mgear4's drag_n_drop_install python script,
there is the function to get maya window pointer,
![image](https://user-images.githubusercontent.com/5518827/190881867-347d26be-f436-4324-b0a1-3865fa5f6642.png)
type<long> is removed in python3,
so the `<=` comparison operator in the if statement should be replaced by `>=`,
I think?

**Comment by miquelcampos** [comment]
Thanks for the feedback @ypypjay  adding it to the WIP project to be fixed
