### ISSUE TITLE
Synoptic: Reset Bind Pose function assumes the dagNode is "dagNode1"

### ISSUE THREAD

**Issue by hoover900** [mgear-dev/mgear#166]
The reset Bind Pose function assumes the dagNode of the rig is "dagNode1".
https://github.com/miquelcampos/mgear/blob/cc352d89a3930697b49ecc5e7152fb214c0f4879/scripts/mgear/maya/synoptic/utils.py#L820

**Comment by miquelcampos** [comment]
Has I comment in the user group. I will check this ticket and update the logic to use message connections.

**Comment by miquelcampos** [comment]
This issue was moved to mgear-dev/synoptic#4
