### ISSUE TITLE
mGear: skin: exportSkinPack always brings up dialogue

### ISSUE THREAD

**Issue by RafaelVillar** [mgear-dev/mgear#179]
exportSkinPack: The dialogue is always brought up when ran, unlike the other export options that only do so when a path is not provided.

Other suggestions, this function should be broken up into two. One that only accepts a path, and another that brings up the dialogue and a start path for dialogue box.

**Comment by miquelcampos** [comment]
This issue was moved to mgear-dev/mgear_core#4
