### ISSUE TITLE
Shifter: Right click context menu for guides

### ISSUE THREAD

**Issue by miquelcampos** [mgear-dev/mgear#187]
Options:

- [x] Build component
- [ ] Build component + child
- [ ] Update component
- [x] Update guide (Not working if root guide is not selected)
- [x] Duplicate mirror
- [ ] Duplicate mirror replace
- [ ] Reload selected component
- [x] Reload all components
- [x] Export guide
- [x] Guide x ray curve toggle

**Comment by miquelcampos** [comment]
![image](https://user-images.githubusercontent.com/1050212/205190341-89481866-1192-468c-9a4e-3f783dcd1ccd.png)

**Comment by liudger** [comment]
Maybe also add snap feature. So you can easily snap a guide point to something. (snap to center for eyes for example)

**Comment by miquelcampos** [comment]
Noted! :)  But since I rely on the first selected object to pop the menu. I am not sure if the logic will be too convoluted. I will think about it

**Comment by liudger** [comment]
Maybe when you have more than 1 object selected you get other options also? A lot to think about it.
