### ISSUE TITLE
Rigbits: PROXY GEO 

### ISSUE THREAD

**Issue by miquelcampos** [mgear-dev/mgear#196]
Tool to create proxy geometry like 3ds Max CAT or Ragdoll.

- [x] create capsules or boxes
- [x] after editing it can be stored in json file for the next build
- [x]  option to combine it or keep it separated by joint. Serialization should support this option
- [ ] color coding system like ctl
- [x] axis direction alignment
- [x] duplicate and mirror
- [ ]  auto color based on mirror
- [ ] Use proxy volume for  Unreal Engine and Ragdoll collision volume.  Related to #117 

Building default positions

- Build for each child: will create one proxy geo to reach the position of each child. For example the metacarpal or finger
- Build  volume to the  far child or closest child
- Build align to joint orientation or to next/child joint option
- Build centered: Build in center
   - if child  and parent will build 50% between,
   - if not child but selected in order will create in the middle 50% adjusted or from previous to next selection (last selected joint will not have proxy geo)

MEMO:

- Joint should store proxy geo build data for rebuild and collection? yes
- for example rebuild from combined
- but should support multiple volumes?? yes
- how to handle when deleting proxy? can be deleted directly, because we will store the rebuild data in the joint
- option to add or replace proxy when generate. For example to add more than one proxy to a joint
- proxy geo is parented under the joint. When combined will apply skinning and combine in a single mesh outside of the joint hierarchy
- FBX export tool should have a checker to ensure there are no proxy geo in the joint hierarchy #117 
-  combine all or only selected. 

![image](https://user-images.githubusercontent.com/1050212/208024856-1ab8a39f-db59-4b25-a84a-c9f976cefda3.png)
![image](https://user-images.githubusercontent.com/1050212/208024998-616c011a-9bef-42e9-920a-f451b76c2416.png)
![image](https://user-images.githubusercontent.com/1050212/208025100-63d33472-71d2-448f-b028-1197f8910d17.png)

**Comment by miquelcampos** [comment]
@mottosso Hi!  I am preparing this new tool for mGear. I didn't check yet in Ragdoll API but will be cool if we can re-use the proxy geo generated here to create the volumes in Ragdoll.  Do you think that is possible?
Just wanted to add this note here, so I don't forget to research this later ;)

**Comment by mottosso** [comment]
Yes, that should be possible.

Ragdoll is forgiving with regards to the topology of the meshes; they don't need to be closed volumes or have any particular edge or polygon layout. It will look only at the points and generate a closed convex hull from that. So the one thing your tool could do if it needs more precision in the mesh, like a foot or around the clavicle area, is to split a mesh such that there are multiple polygon islands. An island being some set of points that are connected in some way. For example, if you make 2 Maya polygon spheres and `Combine` them, they will be one mesh that you can connect to Ragdoll, but two separate islands. Ragdoll will look at each individual island when generating the collision geometry, so the more islands you have the greater precision you can get. Each island is convex, but the final combined shape doesn't have to be.

See here for examples and details.

- https://learn.ragdolldynamics.com/releases/2022.02.28/#automatic-mesh-islands

**Comment by miquelcampos** [comment]
@mottosso Thanks for the heds up and info!  The idea is to provide a mechanism to combine  and separate the proxy geos, I will take in consideration the convex thing :)

**Comment by miquelcampos** [comment]
WIP image
![image](https://user-images.githubusercontent.com/1050212/216541862-c359dea2-7c7c-4a0f-a9c1-5fc3b9df0f7a.png)

**Comment by miquelcampos** [comment]
![image](https://user-images.githubusercontent.com/1050212/220002891-ba275fa5-e23a-4b09-99c1-7b4bfd391f95.png)
![image](https://user-images.githubusercontent.com/1050212/220017076-5f34d2b7-3dc8-4059-b897-a8dd2626c3c5.png)
