### ISSUE TITLE
Shifter: Guide Import error

### ISSUE THREAD

**Issue by liudger** [mgear-dev/mgear#201]
When importing the whole guide something goes wrong.

```
1.21053791046 time elapsed running draw_guide
# Traceback (most recent call last):
#   File "/Users/liudger/Library/Preferences/Autodesk/maya/modules/scripts/mgear/shifter/guide_template_explorer.py", line 103, in import_template
#     io.import_partial_guide(conf=template)
#   File "/Users/liudger/Library/Preferences/Autodesk/maya/modules/scripts/mgear/shifter/io.py", line 143, in import_partial_guide
#     partial_names, partial_idx = rig.guide.draw_guide(partial, initParent)
#   File "/Users/liudger/Library/Preferences/Autodesk/maya/modules/scripts/mgear/core/utils.py", line 232, in wrap
#     raise e
# RuntimeError: setAttr: Error reading data element number 1: 
# 
```
It looks like it tries to import the partial guide?

Maya 2020 MacOS

**Comment by miquelcampos** [comment]
Hi @liudger 

I understand this is when import from the shifter >> Guides templates sample, Correct? or is another serialised guide?

**Comment by liudger** [comment]
![image](https://user-images.githubusercontent.com/4112111/212478405-7825ce0c-47c9-49ae-aea5-1e0632771dd0.png)
from this menu from the shifter guide manager, but it seems that it could have been something in the guid itself that caused the error. It seems to work now again.
If needed I could open old file and try to find why it happened

**Comment by miquelcampos** [comment]
If it this is one off I think is not needed for further research.  
I will close that ticket but feel free to re-open it if you find more information about the topic. Thanks
