### ISSUE TITLE
anim_utils uses dict.iteritems() and errors in Python 3

### ISSUE THREAD

**Issue by chris-lesage** [mgear-dev/mgear#203]
Line 2329 of mgear/core/**anim_utils.py**

`for frame, matchDict in matchMatrix_dict.iteritems():`

Should be changed to:

`for frame, matchDict in matchMatrix_dict.items():`

Or, use a similar Python version check as **utils.py** on lines 115 to 119.

**Comment by miquelcampos** [comment]
Thanks for the heads up @chris-lesage  I will check that
