### ISSUE TITLE
Feature: hide node inputs for controls

### ISSUE THREAD

**Issue by liudger** [mgear-dev/mgear#204]
To improve speed it could be a nice feature if build is final that it hide these nodes
![image](https://user-images.githubusercontent.com/4112111/212478027-c8205a81-1a94-43db-9797-05df20e313b7.png)
This will improve selection performance and it looks cleaner:)
Normally I would do this as a post step. But maybe it's something you can set with the Guide Settings? 
![image](https://user-images.githubusercontent.com/4112111/212478528-c25ad089-cadd-4f1b-8c4d-7150236746c4.png)
When Debug Mode is final that it will clean the control nodes.
There is a command for this ` isHistoricallyInteresting`

**Comment by miquelcampos** [comment]
Hi @liudger  
Thanks for the suggestion. I am already hiding some nodes by unchecking ```isHistoricallyInteresting```
But yes, definitely we can hide it all.
I will add the ticket to the To Do list

**Comment by miquelcampos** [comment]
@liudger  I did it. But instead of navigating all the connections in controls, I do it all at once from the top node.

I am curious how you are doing it with your custom step. is it the same I did?
