### ISSUE TITLE
anim_picker: Reading data file which uses ANIM_PICKER_PATH token is not working

### ISSUE THREAD

**Issue by mattschwarzAnim** [mgear-dev/mgear#210]
The `PICKER_DATA` node which you can see in the pictures doesn´t return any error. However, the picker window is empty as it returns no data:
![image](https://user-images.githubusercontent.com/6480036/215102606-92decfb9-c3e1-493e-8e01-c21620f1d06e.png)

The problem seems to be two different issues:

1. No token conversion is currently happening on the `path.exists` check.
https://github.com/mgear-dev/mgear4/blob/f6046994b586395c067a0dd3c6c13d31a240123f/release/scripts/mgear/anim_picker/picker_node.py#L264

As a quick test I used the protected method to add the conversion:
`        if not os.path.exists(file_handlers._convert_path_token(file_path)):`

2. The `@convert_path_token` decorator does not seems to work if the `file_path` variable is passed as a arg.
https://github.com/mgear-dev/mgear4/blob/f6046994b586395c067a0dd3c6c13d31a240123f/release/scripts/mgear/anim_picker/picker_node.py#L267

When I pass it as a kwarg it returns the expected result
`        return file_handlers.read_data_file(file_path=file_path)`

**Comment by miquelcampos** [comment]
Hi @mattschwarzAnim  Thanks for reporting this. 
I have added to the current WIP project and I will check it ASAP :)

**Comment by miquelcampos** [comment]
Hi @mattschwarzAnim 
Almos 2 years, but I think is fixed now 😅 
It will be included in mGear 5.0
Cheers!
