### ISSUE TITLE
Feature: Channel wrangler move bool channels

### ISSUE THREAD

**Issue by liudger** [mgear-dev/mgear#217]
Change wrangler can't move bool and those channels pop to the top. This is undesired.
If left and right have different channel layout when building you can't fix this to look the same. (not sure why they are not exactly  mirrored)

![image](https://user-images.githubusercontent.com/4112111/219952998-51f97897-f62c-48e5-8de5-b6eb7ce41957.png)

CGMToolbox can change the order. Maybe peek how they do it?
cgm.core.tools.attrTools

I'll have a look at the code when I have time

**Comment by miquelcampos** [comment]
@liudger sorry for the super late reply. I will check this ASAP. Thanks for the feedback
