### ISSUE TITLE
Dialog windows are positioned incorrectly on multi-display setups

### ISSUE THREAD

**Issue by Ruuttu** [mgear-dev/mgear#223]
![two_screens](https://user-images.githubusercontent.com/11808216/41029652-da0d5068-6984-11e8-94d4-ebb579ea5045.png)

Some mGear windows that are supposed to appear in the center of the screen are positioned incorrectly on machines with multiple displays. With two screens, the dialogs appear split halfway between them, for example.

Including 
- Simple Rig Tool
- Channel Wrangler
- Synoptic
- Soft Tweaks
- The Settings window for guide components

This shouldn't prevent anyone from working since the window can be dragged to where it's more readable. However, it could be annoying especially when working with a guide, where all settings are housed in separate dialog windows for every component.

**Comment by miquelcampos** [comment]
Hi @Ruuttu Thanks for the super nice feedback!

I would like to give priority to other issues/tickets, but if you feel like this is something that you can do, your contribution is really welcome :)

Thanks,
Miquel
