### ISSUE TITLE
Game Tools Export: Set index is incorrect, re-connect fails

### ISSUE THREAD

**Issue by cdardis** [mgear-dev/mgear#231]
The set index referenced in `game_tools.py` can be invalid if a `Custom Controllers Group` is specified by the user in shifter

```
    # check the folder and script
    # if the target name exist abort and request another name

    deformer_jnts = rigTopNode.rigGroups[3].connections()[0].members()
```

![image](https://user-images.githubusercontent.com/3675672/236710574-67eded07-3dd6-4137-a2fd-f5dd1f2232e6.png)

In the above example, with a Custom Controller group - rigTopNode.rigGroup[i] , i != 3, i=4

**Comment by miquelcampos** [comment]
@cdardis thanks for te feedback! I have added the ticket to the project to do list
