### ISSUE TITLE
Build from guide template file incompatible with EPIC components

### ISSUE THREAD

**Issue by Lohult** [mgear-dev/mgear#238]
Hi @miquelcampos 
It turns out that building from a guide file is incompatible with EPIC components. In the EPIC components `__init__.py` `jnt_pos` gets appended with` self.guide.guide_locators` which is referencing what is in the scene at the time thus it will return None because the guide is not in the scene.

I tried finding an alternative way of accessing specific guide locators. Apart from the root, for which self.root exists, you cannot seem to get any of the locators under the root, like the spineTop or spineBase in the case of the EPIC spine.

the guide file with the component dictionary has those locators in there but they are keys with position values. Perhaps updating what information gets stored in the guide file will help, like adding "guide locators" to the .sgt file per component?

**Comment by miquelcampos** [comment]
Hi @Lohult  
Sorry, I didn't reply before to this. That is a very nasty bug. I will fix it ASAP.
Thanks for the feedback!

**Comment by miquelcampos** [comment]
@Lohult this was fixed in the issue #112
