### ISSUE TITLE
Shifter embed guide information in rig

### ISSUE THREAD

**Issue by miquelcampos** [mgear-dev/mgear#248]
- option to build guide from the rig
- option to snap guide to rig position. We can use the rig to edit character proportions

**Comment by miquelcampos** [comment]
@Lohult  😄 

![2023-09-06_19h52_48](https://github.com/mgear-dev/mgear4/assets/1050212/fa3fdcc3-1048-4792-b2b2-f53ab1d86cec)

**Comment by Lohult** [comment]
@miquelcampos you are my rigging Santa Claus, Miquel. Thanks for this.

**Comment by miquelcampos** [comment]
@Lohult it is not perfect the data will be embedded at generation time. Old rigs can't extract the guide 😅
