### ISSUE TITLE
Error while mgear menu generation on startup 

### ISSUE THREAD

**Issue by araifractal** [mgear-dev/mgear#265]
Getting this error while startup
```
Error: TypeError: file C:\fractal\packages\mgear\4.1.0\release\scripts\mgear\rigbits\weightNode_io.py line 135: '>' not supported between instances of 'NoneType' and 'str'
```
I've fixed this issue on my system by replacing this line...
```
plugin_utils.load_plugin_with_path(plugin_list, "weightDriver/plug-ins")
```
with this....
```
plugin_utils.load_plugin_with_path(plugin_list, "plug-ins\\weightDriver.mll")
```

This was tested with Maya 2022 and Maya 2024

**Comment by miquelcampos** [comment]
@araifractal Thanks for the feedback. I will check this ASAP

**Comment by miquelcampos** [comment]
@araifractal  I think this was fixed here https://github.com/mgear-dev/mgear4/pull/267

Can you confirm on your side?  
For the moment I will close this ticket. But please open it again if the error happens again. Thanks
