### ISSUE TITLE
Guide Data embedded in the rig node has a bug 

### ISSUE THREAD

**Issue by joji2468ng** [mgear-dev/mgear#280]
It seems that I couldn't retrieve guide data embedded in the rig node due to a syntax error in the dictionary in the latest version 4.1.0.

At least, what I found are boolean values. Please make sure to use **True** instead of **true** and **False** instead of **false**. They need to be capitalized. **null** is not a valid keyword. The correct keyword for a null value might be **None** in this case.

Thanks,

![image](https://github.com/mgear-dev/mgear4/assets/11863299/a2804d68-7286-4163-afd1-3d64062f0550)

**Comment by miquelcampos** [comment]
@joji2468ng it is not a bug. Please use json.loads to decode the data 😉

**Comment by joji2468ng** [comment]
Oh, sorry. I will try to use json.loads! Thank you!
