### ISSUE TITLE
weightNode_io and plugin_utils misc issues

### ISSUE THREAD

**Issue by miquelcampos** [mgear-dev/mgear#289]
- Review all the loading logit for weight driver
- get_all_available_plugins only check for .mll. This will not work in other OS

Related with #244 and #267

**Comment by SimonBenAnderson** [comment]
created new branch https://github.com/mgear-dev/mgear4/tree/mgear_289

**Comment by miquelcampos** [comment]
Some feedback from a friend:
I will check this myself ASAP

The latest master commit seems to be mostly fine.
maybe tow little things:

- as pluginVersion class constructor may raise an exception and taking into account that not necessarily all plugins follow the MAJOR.MINOR.PATCH versioning pattern, the get_plugin_version function may fail with an exception but the calling code (weightNode_io.loadWeightPlugin) doesn't really check for that.
- it still doesn't look like paths comparison is properly handled (no normalization to / although os.path.join usage on windows will introduce some \, using .lower() for all platforms while it should only be windows and potentially mac)

also funny enough that you implemented version checking for weightDriver but the code is ignored if there's only one weightDriver plugin found, which doesn't necessarily mean it is a valid version... and on maya 2024 weightDriver version is not capped at 4... so you may still allow loading of a potentially incompatible weightDriver plugin
