### ISSUE TITLE
RBF Manager 2.0: Miscellaneous Improvements

### ISSUE THREAD

**Issue by miquelcampos** [mgear-dev/mgear#299]
- [x] Provide a default name for the weighDriver setup node based on the driver and allow users to rename it, if they wish instead of requiring users to specify a setup name.
- [x] Add a QSplitter between driveDrivenSetupWidget and driveDrivenTableWidget
- [x] Open the UI with the size and the position it had when it was last used.
- [x] Set 'Display Keyable' as the default option. If there are no keyable attributes, then consider 'Display Non-Keyable' as the default.
- [x] Remove a driven setup window and embed the driven setup widget into the UI. 
- [x] Add a button that allows setting both a driver and a controller
- [x] Add a new context menu item in QListWidget for both driver and driven attributes that allow setting your selected attribute to be automatically highlighted in the next operations(the new setup).
- [x] The button layout related to the pose for the table widget was changed after embedding a driven setup widget into the UI. 
- [x] Approximate small float values to zero to clean up data and make it more readable after exporting a file.
- [x] Transitioning to RBFmanager 2.0 and packaging it in a self-contained folder
- [x] Add a new menu item to delete all RBFs in the file menu.
- [ ] Address the bug where the 'Refresh UI' button causes the UI setup to be destroyed.
What happens is: that the driver and driven objects disappear in the UI, even if the setup still exists in the scene.
- [ ] Implement a QListWidget to manage the created weight drivers instead of using a combo box.
- [ ] Implement the behavior of automatically triggering Reevaluate Nodes whenever the user manually inputs pose values.

**Comment by joji2468ng** [comment]
Here is the new layout of the tool. 

The driven widget was embedded and no pop-up window for the driven setup. The plus button, located next to the 'Set' button in the 'Driven' textField, allows you to add another driven. Pressing the plus button will clear both the 'Driven' textField and the 'Driven Attributes' field.

Also, the button with a left arrow icon next to the set button of control and driver allows setting both a controller and a driver simultaneously to reduce clicks. Once creating a weighted driver, It provides a default name for the weighDriver setup node based on the driver name.


![image](https://github.com/mgear-dev/mgear4/assets/11863299/e92007ea-123b-4299-9240-c805037d002d)

**Comment by joji2468ng** [comment]
Besides, Added a new context menu item in QListWidget for both driver and driven attributes that allow setting your selected attribute to be automatically highlighted in the next operations(the new setup).

![image](https://github.com/mgear-dev/mgear4/assets/11863299/2a51fc0b-dd1a-4075-94d8-c561c2838efd)
