### ISSUE TITLE
RBF manager uses f-strings which breaks compatibility with Maya 2020

### ISSUE THREAD

**Issue by chris-lesage** [mgear-dev/mgear#417]
In this thread, a user is trying to use the RBF manager in Maya 2020.
http://forum.mgear-framework.com/t/rbf-manager-importing-rbf/3033/4?u=chrislesage

In order to keep compatibility with Maya 2020, I suggest changing the f-strings to older style string formatting.

Example: **rbf_manager_ui.py line 832**
`print(f"rbfNode: {rbfNode}")`
to
`print("rbfNode: {}".format(rfbNode))`

**Comment by miquelcampos** [comment]
Hi @chris-lesage  Thanks for flagging this issue. I will fix it ASAP :D

**Comment by miquelcampos** [comment]
it was fixed time ago :D
