### ISSUE TITLE
Synoptic: Replace script jobs by callbacks

### ISSUE THREAD

**Issue by miquelcampos** [mgear-dev/mgear#52]
EDIT: implement after: mGear: Callback Manager #165
Replace the scriptjobs for visual feedback with callbacks, for a more robust management with several synoptic window open.
Right now only the latest synoptic view has visual feedback for selected controls.

The call back manager should be independent from synoptic

**Comment by yamahigashi** [comment]
Hi Miquel,
It's my turn, I'll tackle it.

**Comment by miquelcampos** [comment]
Oh! Great :D  Thank you for the help!

btw: please check the contribution document: https://github.com/miquelcampos/mgear/blob/master/CONTRIBUTING.md

Please don't hesitate contacting me if you have any question regarding this issue.

**Comment by miquelcampos** [comment]
Hello @yamahigashi , did you have the chance to advance with this issue?  Thanks

**Comment by miquelcampos** [comment]
Hello @yamahigashi  I will take over this one soon.  I  want to create a callback manager that can be use in other areas. Is it ok for you?  Thanks

**Comment by miquelcampos** [comment]
This issue was moved to mgear-dev/mgear_dist#4
