### ISSUE TITLE
Adding Gravity to spring solver

### ISSUE THREAD

**Issue by miquelcampos** [mgear-dev/mgear#58]
review and merge working version from the forum http://forum.mgear-framework.com/t/mgear-springnode-gravity/796/32

**Comment by herniguerra** [comment]
Please consider adding basic collision volume features. Spring + gravity and collision would be a killer feature

**Comment by miabrahams** [comment]
https://github.com/miabrahams/mgear_solvers
Here is the gravity + collision solver!  I can submit as a pull request if you'd like.

**Comment by miquelcampos** [comment]
Hello @miabrahams  thanks for the link.  I will check it ASAP.
Can you do a Pull request?  I think you will need to fork the mgear4 repo and add the changes first there.  😅

**Comment by miabrahams** [comment]
Pull request sent!  

One other easy extension in the future would be to have a movable plane collider instead of a fixed ground plane. But this is good enough for now!

**Comment by miabrahams** [comment]
Also sorry for going off-topic but I'm having trouble logging into the mgear forums with Google authentication. 

```
Error 400: invalid_request

You can't sign in to this app because it doesn't comply with Google's OAuth 2.0 policy for keeping apps secure.

You can let the app developer know that this app doesn't comply with one or more Google validation rules.
```

**Comment by miabrahams** [comment]
[mGear_spring_test.zip](https://github.com/mgear-dev/mgear4/files/8010546/mGear_spring_test.zip)

Here is a test scene for the new mgear_springGravity solver.
