### ISSUE TITLE
Guide Setting Window auto switch base on selection

### ISSUE THREAD

**Issue by FXTD-ODYSSEY** [mgear-dev/mgear#63]
I add a scriptjob Event to achieve the result below

![maya](https://user-images.githubusercontent.com/40897360/142100780-673c5d00-9f85-4ebe-919e-c62f099250e8.gif)

I think this feature pretty helpful for guide settings modificiation.

**Comment by FXTD-ODYSSEY** [comment]
![image](https://user-images.githubusercontent.com/40897360/142128344-4aae6bc7-4e17-439c-a46e-5392452f8597.png)
Add a menu item to enable/disable this feature.

**Comment by miquelcampos** [comment]
Hello @FXTD-ODYSSEY  thanks for this idea and the other PR.
I really like it, but there is a couple of things.
About the scriptjobs. We don't use it on mGear. Instead, we use callbacks. We have a module to handle that.
The other thing is about your implementation of it. I would like to do something similar to what Softimage XSI had
![image](https://user-images.githubusercontent.com/1050212/142135444-c9639d5c-ff31-4d71-ab35-21c3630c19c1.png)

I am not going to merge this pull request. But I am opening another ticket to implement it https://github.com/mgear-dev/mgear4/issues/65

I hope that is fine with you

Thanks again for the contribution! and please keep it coming! ❤️
