### ISSUE TITLE
missing mgear tab at top menu of maya 

### ISSUE THREAD

**Issue by AmityAshes** [mgear-dev/mgear#76]
After drag and drop install
preferences show that mgear is installed, however the mgear tab is nowhere to be seen
After restarting the program, theres still no mgear tab 
How do I fix this ?

**Comment by miquelcampos** [comment]
Hello @AmityAshes 
are you using Maya 2022? if yes, have you installed pymel for python3? Here is more info related to that topic http://forum.mgear-framework.com/t/mgear-is-not-displayed-in-maya2022/2630

Please in the future use the forum for this kind of support question.  http://forum.mgear-framework.com/
:)

Cheers!

**Comment by AmityAshes** [comment]
Hello Miquel
I apologise for using the wrong section, I infact found the forum shortly
after that post.
It's my first time here and I got confused in the midst of my desperation.

Yes I have according to what maya tells me when I install the app (It says
pymel for python 3 installed just like in the picture) however I think I'm
discovering that, that doesn't mean it's actually installed. Thank you for
assistance

Kind regards
Amity



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by bolach87** [comment]
I've the same problem. Heeeelp

**Comment by Nat3Turner** [comment]
I recently had a similar issue where mgear existed, it was even present as a module but no menu button.

My Solution:
replace ( \modules\scripts\mgear\menu.py line 18 )
   ` if pm.menu(menuId, exists=True):`
with
    `if maya.cmds.menu(menuId, exists=True):`

My testing showed that the PyMel call was returning a garbage reference to `scriptEditorPanel1Window|scriptEditorPanel1|False` and as the call moves recursively down, it, again, calls the menu() a second time, but now menuId == 'False'.  I think PyMel has some issues in this area.  I could not trackdown the ScriptEditorPanel anywhere, and found mayas original menu check worked.

I have not done thorough testing, as I only found this fix Friday.
